#!/usr/bin/env python3
# tools/spv_header.py — embed SPIR-V into a C header so the renderer needs no
# shader file paths at run time.
#
#   python3 tools/spv_header.py quad.vert.spv quad.frag.spv quad_spv.h
import sys


def emit(o, name, path):
    data = open(path, "rb").read()
    o.write("static const unsigned char %s_spv[] = {" % name)
    o.write(",".join(str(b) for b in data))
    o.write("};\n")
    o.write("static const unsigned int %s_spv_len = %u;\n" % (name, len(data)))


def main():
    vert, frag, out = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(out, "w") as o:
        o.write("// generated by tools/spv_header.py — do not edit\n")
        emit(o, "quad_vert", vert)
        emit(o, "quad_frag", frag)


if __name__ == "__main__":
    main()
